name: Domain Fetch
on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日00:00 UTCに実行
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # 依存関係をインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # 現在の時刻を取得して環境変数に保存
    - name: Get current timestamp
      id: timestamp1
      run: echo "RELEASE_TIME=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Get formatted timestamp
      id: timestamp2
      run: echo "FORMATTED_TIME=$(date '+%Y/%m/%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Run script
      run: python app.py

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'domain-list-${{ env.RELEASE_TIME }}'
        release_name: 'Domain List ${{ env.FORMATTED_TIME }}'
        body: "Generated domain list for by ${{ github.run_id }} in ${{ env.FORMATTED_TIME }}"
        draft: false
        prerelease: false

    - name: Upload domain list
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/website.txt
        asset_name: website.txt
        asset_content_type: text/plain
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
